name: Amateur
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      CI: false
    steps:
      - name: Checkout source code.
        uses: actions/checkout@main
        
      - name: Install Dependencies
        run: npm install --force
        
      - name: Build
        run: npm run build
